### ISSUE TITLE
Improve units of measurement

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/health-check#8]
Improve the units of measurement labels, because today the json response could generate a confusing between infos (what's kb, or %, or anything else).

![image](https://user-images.githubusercontent.com/9089383/32151038-b7a34356-bd00-11e7-9215-ada161285cd7.png)

Feel free to propose a solution... Create a new pattern, remove labels or add units in each metric, feel free :wink:

**Comment by andri-de** [comment]
hello robert, i had made a pull request.

**Comment by robertoduessmann** [comment]
Oh, that's good @andri-de . I will check!

**Comment by robertoduessmann** [comment]
- Memory: kb
- Disks: kb
- Processor: %
