### ISSUE TITLE
Get port app config from environment variables

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/health-check#9]
Get port app config from environment variables, to keep the app more generic and customized.

My suggestion is use [github.com/caarlos0/env](http://github.com/caarlos0/env).
I already used in another project [here](https://github.com/robertoduessmann/weather-api/commit/9ef1bcb1dab8ae70a7d8ce62fb862758f24b50b7).

**Comment by andri-de** [comment]
hello robert, i had made a pull ruquest.
Thanks.

**Comment by robertoduessmann** [comment]
Thanks for contribution @andri-de , I will review the pull request right now :grinning:
